from gym_v.envs.gamerl.chess_ranger import GameRLChessRangerQAEnv
from gym_v.envs.gamerl.freecell import GameRLFreecellQAEnv
from gym_v.envs.gamerl.hue import GameRLHueQAEnv
from gym_v.envs.gamerl.jewel2 import GameRLJewel2QAEnv
from gym_v.envs.gamerl.klondike import GameRLKlondikeQAEnv
from gym_v.envs.gamerl.langton_ant import GameRLLangtonAntQAEnv
from gym_v.envs.gamerl.lifegame import GameRLLifegameQAEnv
from gym_v.envs.gamerl.maze import GameRLMazeQAEnv
from gym_v.envs.gamerl.maze_3d import GameRL3dMazeQAEnv
from gym_v.envs.gamerl.minecraft import GameRLMinecraftQAEnv
from gym_v.envs.gamerl.minesweeper import GameRLMinesweeperQAEnv
from gym_v.envs.gamerl.pacman import GameRLPacmanQAEnv
from gym_v.envs.gamerl.pyramidchess import GameRLPyramidChessQAEnv
from gym_v.envs.gamerl.rhythm_game import GameRLRhythmGameQAEnv
from gym_v.envs.gamerl.rubiks_cube import GameRLRubiksCubeQAEnv
from gym_v.envs.gamerl.snake import GameRLSnakeQAEnv
from gym_v.envs.gamerl.sokoban import GameRLSokobanQAEnv
from gym_v.envs.gamerl.space_invaders import GameRLSpaceInvadersQAEnv
from gym_v.envs.gamerl.spider_solitaire import GameRLSpiderSolitaireQAEnv
from gym_v.envs.gamerl.star_battle import GameRLStarBattleQAEnv
from gym_v.envs.gamerl.sudoku import GameRLSudokuQAEnv
from gym_v.envs.gamerl.tangram import GameRLTangramQAEnv
from gym_v.envs.gamerl.tents import GameRLTentsQAEnv
from gym_v.envs.gamerl.tetris import GameRLTetrisQAEnv
from gym_v.envs.gamerl.threed_reconstruction import GameRL3DReconstructionQAEnv
from gym_v.envs.gamerl.tictactoe import GameRLTicTacToeQAEnv
from gym_v.envs.gamerl.turing_machine_2d import GameRL2dTuringMachineQAEnv
from gym_v.envs.gamerl.ultra_tictactoe import GameRLUltraTicTacToeQAEnv
from gym_v.envs.gamerl.word_search import GameRLWordSearchQAEnv
from gym_v.envs.gamerl.zuma import GameRLZumaQAEnv
