from gym_v.envs.reasongym.game_of_life import ReasoningGymGameOfLifeEnv
from gym_v.envs.reasongym.kakurasu import ReasoningGymKakurasuEnv
from gym_v.envs.reasongym.knight_swap import ReasoningGymKnightSwapEnv
from gym_v.envs.reasongym.maze import ReasoningGymMazeEnv
from gym_v.envs.reasongym.mini_sudoku import ReasoningGymMiniSudokuEnv
from gym_v.envs.reasongym.n_queens import ReasoningGymNQueensEnv
from gym_v.envs.reasongym.sudoku import ReasoningGymSudokuEnv
from gym_v.envs.reasongym.survo import ReasoningGymSurvoEnv
from gym_v.envs.reasongym.tower_of_hanoi import ReasoningGymTowerOfHanoiEnv
from gym_v.envs.reasongym.tsumego import ReasoningGymTsumegoEnv
