"""Card coloring counting environment for gym-v (self-contained)."""

from __future__ import annotations

from collections import deque
from importlib import resources
from textwrap import dedent
from typing import Any

from PIL import Image, ImageDraw, ImageFont

from gym_v import Env, Observation
from gym_v.logger import get_logger

logger = get_logger()


class RLVECardColoringCountingEnv(Env):
    """RLVE Card Coloring Counting as a single-turn environment.

    Count the number of distinct coloring schemes for N cards using R red,
    G green, and B blue colors, where two colorings are considered the same
    if one can be transformed into the other by applying shuffle methods.

    The shuffle methods generate a permutation group, and we use Burnside's
    lemma to count equivalence classes.
    """

    assets_dir = resources.files("gym_v.envs") / "assets"

    prompt_template = r"""You have **{N}** cards, and there are some card shuffling methods. Each shuffle method is described by a row of {N} integers: X_1, X_2, ..., X_{N}. After applying a shuffle method, the card at position i moves to the position X_i. The shuffling methods are as follows:
{shuffling_methods}

Now, you need to color these cards into **{R}** red cards, **{G}** green cards, and **{B}** blue cards.
Determine how many distinct coloring schemes exist, where two colorings are considered the same if and only if one can be transformed into the other by any combination of the available shuffling methods (shuffles may be applied multiple times and in any order).

**Output Format:** Your final answer should be a single integer — the total number of distinct coloring schemes, considering equivalence under the shuffling methods."""

    def __init__(
        self,
        N: int = 8,
        K: int = 2,
        num_players: int = 1,
        image_width: int = 800,
        image_height: int = 600,
        **kwargs: Any,
    ):
        super().__init__(**kwargs)
        self._N = N
        self._K = K
        self.num_players = num_players
        self._agent_ids = {f"agent_{i}" for i in range(num_players)}
        self._image_width = image_width
        self._image_height = image_height

        self._n: int | None = None
        self._k: int | None = None
        self._r: int | None = None
        self._g: int | None = None
        self._b: int | None = None
        self._shuffling_methods: list[tuple[int, ...]] | None = None
        self._prompt: str | None = None
        self._oracle_answer: int | None = None
        self._last_image: Image.Image | None = None

    @property
    def description(self) -> str:
        return dedent(
            """
            Card Coloring Counting Problem:

            Given N cards and K shuffling methods (permutations), count the
            number of distinct ways to color the cards using:
            - R red cards
            - G green cards
            - B blue cards

            Two colorings are equivalent if one can be transformed into the
            other by applying any combination of the shuffling methods.

            This uses Burnside's lemma to count equivalence classes under
            the group action generated by the shuffle permutations.

            In the visualization:
            - Cards are shown numbered 1 to N
            - Each shuffling method shows how cards are permuted
            - Color requirements (R, G, B) are displayed

            Output format: A single integer (the number of distinct colorings).
            """
        ).strip()

    def _get_state_text(self) -> str:
        """Return text representation of the card coloring problem."""
        if self._n is None or self._shuffling_methods is None:
            return ""
        lines = [
            f"N = {self._n} cards",
            f"Colors: {self._r} Red, {self._g} Green, {self._b} Blue",
            "Shuffling methods:",
        ]
        for i, perm in enumerate(self._shuffling_methods):
            lines.append(f"  Method {i + 1}: " + " ".join(map(str, perm)))
        return "\n".join(lines)

    def reset(
        self, *, seed: int | None = None, options: dict[str, Any] | None = None
    ) -> tuple[dict[str, Observation], dict[str, Any]]:
        super().reset(seed=seed)

        self._generate()
        self._prompt = self._prompt_generate()
        self._last_image = self.render()

        state_text = self._get_state_text()
        obs = Observation(
            image=self._last_image,
            text=None,
            metadata={
                "state_text": state_text,
                "text_prompt": self._prompt,
            },
        )
        info = {
            "oracle_answer": str(self._oracle_answer),
        }
        return {agent_id: obs for agent_id in self._agent_ids}, {
            agent_id: info for agent_id in self._agent_ids
        }

    def inner_step(
        self, action: dict[str, str]
    ) -> tuple[
        dict[str, Observation],
        dict[str, float],
        dict[str, bool],
        dict[str, bool],
        dict[str, Any],
    ]:
        agent_id = next(iter(self._agent_ids))
        action_str = action[agent_id]
        reward = float(self._score_answer(action_str))
        state_text = self._get_state_text()
        obs = Observation(
            image=self._last_image,
            text=None,
            metadata={
                "state_text": state_text,
                "text_prompt": self._prompt,
            },
        )
        info = {
            "oracle_answer": str(self._oracle_answer),
        }

        terminated = True
        truncated = False

        return (
            {agent_id: obs for agent_id in self._agent_ids},
            {agent_id: reward for agent_id in self._agent_ids},
            {
                **{agent_id: terminated for agent_id in self._agent_ids},
                "__all__": terminated,
            },
            {
                **{agent_id: truncated for agent_id in self._agent_ids},
                "__all__": truncated,
            },
            {agent_id: info for agent_id in self._agent_ids},
        )

    def _generate(self) -> None:
        """Generate a card coloring counting problem instance (ported from RLVE)."""
        N = self._N
        K = self._K

        if N < 2:
            raise ValueError("N should be greater than or equal to 2")
        if K < 0:
            raise ValueError("K should be greater than or equal to 0")

        # Randomly generate R, G, B such that R + G + B = N
        R = int(self.np_random.integers(0, N + 1))
        remaining = N - R
        G = int(self.np_random.integers(0, remaining + 1))
        B = remaining - G
        RGB = [R, G, B]
        self.np_random.shuffle(RGB)
        R, G, B = RGB

        # Randomly select K permutations from all N-permutations
        selected_perms = []
        while len(selected_perms) < K:
            perm_list = list(range(1, N + 1))
            self.np_random.shuffle(perm_list)
            perm = tuple(perm_list)
            selected_perms.append(perm)

        # Generate the subgroup generated by selected_perms
        def perm_compose(p1: tuple[int, ...], p2: tuple[int, ...]) -> tuple[int, ...]:
            # Compose two permutations (1-based indexing)
            return tuple(p1[p2[i] - 1] for i in range(len(p1)))

        # Start with the identity permutation
        identity = tuple(range(1, N + 1))
        subgroup = set()
        queue = deque()
        subgroup.add(identity)
        queue.append(identity)

        for perm in selected_perms:
            perm_tuple = tuple(perm)
            if perm_tuple not in subgroup:
                subgroup.add(perm_tuple)
                queue.append(perm_tuple)

        while queue:
            current = queue.popleft()
            for perm in selected_perms:
                perm_tuple = tuple(perm)
                composed = perm_compose(current, perm_tuple)
                if composed not in subgroup:
                    subgroup.add(composed)
                    queue.append(composed)

        subgroup_perms = [list(perm) for perm in subgroup]

        def solve(n: int, red: int, blue: int, green: int, v: list[int]) -> int:
            # Initialize visited array for cycle detection
            vis = [False] * (n + 1)

            # dp table dimensions dynamically based on R, G, B counts
            # dp[r][b][g] stores the number of ways to arrange r red, b blue, g green items
            dp = [
                [[0 for _ in range(green + 1)] for _ in range(blue + 1)]
                for _ in range(red + 1)
            ]

            num_cycles = 0
            cycle_sizes = [0] * (n + 1)  # Stores the length of each cycle found

            # Step 1: Detect cycles in the permutation
            for i in range(1, n + 1):
                if not vis[i]:
                    x = i
                    len_cycle = 0
                    while not vis[x]:
                        len_cycle += 1
                        vis[x] = True
                        x = v[x]  # Follow the permutation cycle
                    num_cycles += 1
                    cycle_sizes[num_cycles] = len_cycle

            # Step 2: Initialize DP for no items
            dp[0][0][0] = 1

            # Step 3: Populate DP table using cycle lengths
            # Iterate through each detected cycle
            for x_idx in range(1, num_cycles + 1):
                current_size = cycle_sizes[x_idx]
                # Iterate backwards through the DP table to use previous states
                for i in range(red, -1, -1):
                    for j in range(blue, -1, -1):
                        for k in range(green, -1, -1):
                            # If current cycle size can be used for red items
                            if i >= current_size:
                                dp[i][j][k] += dp[i - current_size][j][k]
                            # If current cycle size can be used for blue items
                            if j >= current_size:
                                dp[i][j][k] += dp[i][j - current_size][k]
                            # If current cycle size can be used for green items
                            if k >= current_size:
                                dp[i][j][k] += dp[i][j][k - current_size]

            return dp[red][blue][green]

        def work(
            N: int, R: int, G: int, B: int, subgroup_perms: list[list[int]]
        ) -> int:
            total_ans = 0
            num_of_perms = len(subgroup_perms)
            for perm_list in subgroup_perms:
                # Create a 1-indexed permutation list 'v_current' from the input 'perm_list'
                v_current = [0] * (N + 1)
                for idx in range(N):
                    v_current[idx + 1] = perm_list[
                        idx
                    ]  # Adjusting for 1-based indexing

                total_ans += solve(N, R, B, G, v_current)

            # Only add the identity permutation if it is not already in subgroup_perms
            v_identity = [i for i in range(1, N + 1)]
            if v_identity not in subgroup_perms:
                num_of_perms += 1
                v_identity_full = [0] + v_identity  # 1-based indexing
                total_ans += solve(N, R, B, G, v_identity_full)

            return total_ans // num_of_perms

        reference_answer = work(N, R, G, B, subgroup_perms)

        if reference_answer <= 0:
            raise RuntimeError("Generated reference answer is not positive")

        self._n = N
        self._k = K
        self._r = R
        self._g = G
        self._b = B
        self._shuffling_methods = selected_perms
        self._oracle_answer = reference_answer

    def _prompt_generate(self) -> str:
        """Generate the prompt text for the problem."""
        if self._n is None:
            raise RuntimeError("No problem generated")
        return self.prompt_template.format(
            N=self._n,
            R=self._r,
            G=self._g,
            B=self._b,
            shuffling_methods="\n".join(
                " ".join(map(str, perm)) for perm in self._shuffling_methods
            ),
        )

    def _process(self, answer: str | None) -> int | None:
        """Process the answer string into an integer."""
        if answer is not None:
            answer = answer.strip()
            try:
                int_answer = int(answer)
                return int_answer
            except ValueError:
                return None
        else:
            return None

    def _score_answer(self, answer: str) -> float:
        """Score the answer based on (min/max)^beta strategy from RLVE.

        Returns:
            -1.0: wrong format (not an integer)
            -1.0: answer <= 0 (invalid)
            0.0 to 1.0: (min(gold, answer) / max(gold, answer))^10
        """
        processed_result = self._process(answer)
        if processed_result is not None:
            if processed_result <= 0:
                return 0.0
            a, b = self._oracle_answer, processed_result
            return (min(a, b) / max(a, b)) ** 10.0
        else:
            return 0.0

    def render(self) -> Image.Image | list[Image.Image] | None:
        """Render the card coloring counting problem as a beautiful image.

        Shows:
        - N cards arranged in a row
        - Each shuffling method as an arrow diagram
        - Color requirements (R red, G green, B blue)
        """
        if self._n is None:
            raise RuntimeError("No problem generated")

        width = self._image_width
        height = self._image_height

        img = Image.new("RGB", (width, height), (255, 255, 255))
        draw = ImageDraw.Draw(img)

        # Load font
        font_path = self.assets_dir / "DejaVuSans.ttf"
        if font_path.exists():
            font_large = ImageFont.truetype(str(font_path), 24)
            font_medium = ImageFont.truetype(str(font_path), 18)
            font_small = ImageFont.truetype(str(font_path), 14)
        else:
            font_large = ImageFont.load_default()
            font_medium = ImageFont.load_default()
            font_small = ImageFont.load_default()

        # Title
        title = "Card Coloring Problem"
        bbox = draw.textbbox((0, 0), title, font=font_large)
        tw = bbox[2] - bbox[0]
        draw.text((width // 2 - tw // 2, 20), title, fill=(30, 30, 30), font=font_large)

        # Draw cards
        y_cards = 70
        card_width = 40
        card_height = 60
        card_spacing = max(
            10,
            (width - 80 - self._n * card_width) // (self._n - 1) if self._n > 1 else 10,
        )
        start_x = (width - (self._n * card_width + (self._n - 1) * card_spacing)) // 2

        for i in range(self._n):
            x = start_x + i * (card_width + card_spacing)
            # Draw card
            draw.rectangle(
                [x, y_cards, x + card_width, y_cards + card_height],
                fill=(240, 240, 240),
                outline=(50, 50, 50),
                width=2,
            )
            # Draw card number
            label = str(i + 1)
            bbox = draw.textbbox((0, 0), label, font=font_medium)
            label_w = bbox[2] - bbox[0]
            label_h = bbox[3] - bbox[1]
            draw.text(
                (
                    x + card_width // 2 - label_w // 2,
                    y_cards + card_height // 2 - label_h // 2,
                ),
                label,
                fill=(30, 30, 30),
                font=font_medium,
            )

        # Draw color requirements
        y_colors = y_cards + card_height + 30
        colors_text = (
            f"Color Requirements: {self._r} Red, {self._g} Green, {self._b} Blue"
        )
        bbox = draw.textbbox((0, 0), colors_text, font=font_medium)
        tw = bbox[2] - bbox[0]
        draw.text(
            (width // 2 - tw // 2, y_colors),
            colors_text,
            fill=(30, 30, 30),
            font=font_medium,
        )

        # Draw color boxes
        y_boxes = y_colors + 30
        box_size = 24
        box_spacing = 20
        color_data = [
            ("Red", (255, 99, 71), self._r),
            ("Green", (75, 192, 75), self._g),
            ("Blue", (54, 162, 235), self._b),
        ]

        total_width = len(color_data) * box_size + (len(color_data) - 1) * box_spacing
        start_x_boxes = (width - total_width) // 2

        for idx, (name, color, count) in enumerate(color_data):
            x = start_x_boxes + idx * (box_size + box_spacing)
            draw.rectangle(
                [x, y_boxes, x + box_size, y_boxes + box_size],
                fill=color,
                outline=(30, 30, 30),
                width=2,
            )

        # Draw shuffling methods section
        y_shuffle = y_boxes + box_size + 40
        shuffle_title = f"Shuffling Methods ({self._k} methods):"
        draw.text((40, y_shuffle), shuffle_title, fill=(30, 30, 30), font=font_medium)

        y_shuffle += 30
        max_methods_to_show = min(5, self._k)

        for method_idx in range(max_methods_to_show):
            if method_idx >= len(self._shuffling_methods):
                break

            perm = self._shuffling_methods[method_idx]
            method_text = f"Method {method_idx + 1}: " + " ".join(map(str, perm))
            draw.text((60, y_shuffle), method_text, fill=(60, 60, 60), font=font_small)
            y_shuffle += 25

        if self._k > max_methods_to_show:
            draw.text(
                (60, y_shuffle),
                f"... and {self._k - max_methods_to_show} more methods",
                fill=(100, 100, 100),
                font=font_small,
            )
            y_shuffle += 25

        # Draw explanation
        y_explain = y_shuffle + 20
        explanation_lines = [
            "Two colorings are equivalent if one can be transformed",
            "into the other using any combination of shuffle methods.",
            "",
            "Count the number of distinct coloring schemes.",
        ]

        for line in explanation_lines:
            draw.text((40, y_explain), line, fill=(100, 100, 100), font=font_small)
            y_explain += 20

        return img
